font_size       14
font_family     GeistMono Nerd Font

macos_option_as_alt left

window_margin_width 5
hide_window_decorations titlebar-only
macos_titlebar_color background
macos_show_window_title_in none

# tab_title_template "{title[title.rfind('/')+1:]}"
# tab_title_template "{title.split('/')[-1]}"
tab_title_template "{index}"

background_opacity 0.5
background_blur 50


# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME


# defaults write com.apple.dock autohide-delay -float 0; killall Dock
